# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - master
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/extendedlocation/

pr:
  branches:
    include:
      - master
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/extendedlocation/

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: extendedlocation
    Artifacts:
      - name: azure-resourcemanager-extendedlocation
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerextendedlocation
