# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/deviceupdate/
    exclude:
      - sdk/deviceupdate/pom.xml
      - sdk/deviceupdate/azure-iot-deviceupdate/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/deviceupdate/
    exclude:
      - sdk/deviceupdate/pom.xml
      - sdk/deviceupdate/azure-iot-deviceupdate/pom.xml

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: deviceupdate
    Artifacts:
      - name: azure-iot-deviceupdate
        groupId: com.azure
        safeName: azureiotdeviceupdate
      - name: azure-resourcemanager-deviceupdate
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerdeviceupdate
      - name: azure-iot-deviceupdate-demo
        groupId: com.azure
        safeName: azureiotdeviceupdatedemo
        releaseInBatch: ${{ parameters.release_azureiotdeviceupdatedemo }}

parameters:
  - name: release_azureiotdeviceupdatedemo
    displayName: azure-iot-deviceupdate-demo
    type: boolean
    default: true
