// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.support.implementation;

import com.azure.core.http.rest.Response;
import com.azure.core.http.rest.SimpleResponse;
import com.azure.core.util.Context;
import com.azure.core.util.logging.ClientLogger;
import com.azure.resourcemanager.support.fluent.ResourceProvidersClient;
import com.azure.resourcemanager.support.fluent.models.SupportTicketResourceIdLookUpResponseInner;
import com.azure.resourcemanager.support.models.ResourceProviders;
import com.azure.resourcemanager.support.models.SupportTicketResourceIdLookUpResponse;
import com.azure.resourcemanager.support.models.SupportTicketResourceIdLookupRequest;

public final class ResourceProvidersImpl implements ResourceProviders {
    private static final ClientLogger LOGGER = new ClientLogger(ResourceProvidersImpl.class);

    private final ResourceProvidersClient innerClient;

    private final com.azure.resourcemanager.support.SupportManager serviceManager;

    public ResourceProvidersImpl(
        ResourceProvidersClient innerClient, com.azure.resourcemanager.support.SupportManager serviceManager) {
        this.innerClient = innerClient;
        this.serviceManager = serviceManager;
    }

    public SupportTicketResourceIdLookUpResponse supportTicketResourceIdLookUp(
        SupportTicketResourceIdLookupRequest supportTicketResourceIdLookupRequest) {
        SupportTicketResourceIdLookUpResponseInner inner =
            this.serviceClient().supportTicketResourceIdLookUp(supportTicketResourceIdLookupRequest);
        if (inner != null) {
            return new SupportTicketResourceIdLookUpResponseImpl(inner, this.manager());
        } else {
            return null;
        }
    }

    public Response<SupportTicketResourceIdLookUpResponse> supportTicketResourceIdLookUpWithResponse(
        SupportTicketResourceIdLookupRequest supportTicketResourceIdLookupRequest, Context context) {
        Response<SupportTicketResourceIdLookUpResponseInner> inner =
            this
                .serviceClient()
                .supportTicketResourceIdLookUpWithResponse(supportTicketResourceIdLookupRequest, context);
        if (inner != null) {
            return new SimpleResponse<>(
                inner.getRequest(),
                inner.getStatusCode(),
                inner.getHeaders(),
                new SupportTicketResourceIdLookUpResponseImpl(inner.getValue(), this.manager()));
        } else {
            return null;
        }
    }

    private ResourceProvidersClient serviceClient() {
        return this.innerClient;
    }

    private com.azure.resourcemanager.support.SupportManager manager() {
        return this.serviceManager;
    }
}
