/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.avs.v2019_08_09_preview.models;

import java.util.Collection;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.microsoft.rest.ExpandableStringEnum;

/**
 * Defines values for DatastoreBackingType.
 */
public final class DatastoreBackingType extends ExpandableStringEnum<DatastoreBackingType> {
    /** Static value NFSv3 for DatastoreBackingType. */
    public static final DatastoreBackingType NFSV3 = fromString("NFSv3");

    /** Static value iSCSI for DatastoreBackingType. */
    public static final DatastoreBackingType I_SCSI = fromString("iSCSI");

    /**
     * Creates or finds a DatastoreBackingType from its string representation.
     * @param name a name to look for
     * @return the corresponding DatastoreBackingType
     */
    @JsonCreator
    public static DatastoreBackingType fromString(String name) {
        return fromString(name, DatastoreBackingType.class);
    }

    /**
     * @return known DatastoreBackingType values
     */
    public static Collection<DatastoreBackingType> values() {
        return values(DatastoreBackingType.class);
    }
}
