# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/network/ci.yml
      - sdk/network/azure-resourcemanager-network/
    exclude:
      - sdk/network/pom.xml
      - sdk/network/azure-resourcemanager-network/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/network/ci.yml
      - sdk/network/azure-resourcemanager-network/
    exclude:
      - sdk/network/pom.xml
      - sdk/network/azure-resourcemanager-network/pom.xml

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: network
    Artifacts:
      - name: azure-resourcemanager-network-generated
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagernetworkgenerated
