// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.singularity.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Describes container's entry-point. */
@Fluent
public final class ContainerEntryPoint {
    /*
     * The entry point program.
     */
    @JsonProperty(value = "program")
    private String program;

    /*
     * Command line arguments to be passed to the program.
     */
    @JsonProperty(value = "programArgs")
    private String programArgs;

    /**
     * Get the program property: The entry point program.
     *
     * @return the program value.
     */
    public String program() {
        return this.program;
    }

    /**
     * Set the program property: The entry point program.
     *
     * @param program the program value to set.
     * @return the ContainerEntryPoint object itself.
     */
    public ContainerEntryPoint withProgram(String program) {
        this.program = program;
        return this;
    }

    /**
     * Get the programArgs property: Command line arguments to be passed to the program.
     *
     * @return the programArgs value.
     */
    public String programArgs() {
        return this.programArgs;
    }

    /**
     * Set the programArgs property: Command line arguments to be passed to the program.
     *
     * @param programArgs the programArgs value to set.
     * @return the ContainerEntryPoint object itself.
     */
    public ContainerEntryPoint withProgramArgs(String programArgs) {
        this.programArgs = programArgs;
        return this;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }
}
