// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.singularity.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.util.logging.ClientLogger;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Describes the quota for the InstanceType series. */
@Fluent
public final class InstanceTypeSeriesQuota {
    /*
     * The identifier for instance type series quota.
     */
    @JsonProperty(value = "id", required = true)
    private String id;

    /*
     * User friendly description for the instance type series.
     */
    @JsonProperty(value = "name", access = JsonProperty.Access.WRITE_ONLY)
    private String name;

    /*
     * The slaTier property.
     */
    @JsonProperty(value = "slaTier")
    private SlaTier slaTier;

    /*
     * Maximum allowed units for the instance type series.
     */
    @JsonProperty(value = "limit", required = true)
    private long limit;

    /*
     * Number of units currently in use.
     */
    @JsonProperty(value = "used", access = JsonProperty.Access.WRITE_ONLY)
    private Long used;

    /**
     * Get the id property: The identifier for instance type series quota.
     *
     * @return the id value.
     */
    public String id() {
        return this.id;
    }

    /**
     * Set the id property: The identifier for instance type series quota.
     *
     * @param id the id value to set.
     * @return the InstanceTypeSeriesQuota object itself.
     */
    public InstanceTypeSeriesQuota withId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get the name property: User friendly description for the instance type series.
     *
     * @return the name value.
     */
    public String name() {
        return this.name;
    }

    /**
     * Get the slaTier property: The slaTier property.
     *
     * @return the slaTier value.
     */
    public SlaTier slaTier() {
        return this.slaTier;
    }

    /**
     * Set the slaTier property: The slaTier property.
     *
     * @param slaTier the slaTier value to set.
     * @return the InstanceTypeSeriesQuota object itself.
     */
    public InstanceTypeSeriesQuota withSlaTier(SlaTier slaTier) {
        this.slaTier = slaTier;
        return this;
    }

    /**
     * Get the limit property: Maximum allowed units for the instance type series.
     *
     * @return the limit value.
     */
    public long limit() {
        return this.limit;
    }

    /**
     * Set the limit property: Maximum allowed units for the instance type series.
     *
     * @param limit the limit value to set.
     * @return the InstanceTypeSeriesQuota object itself.
     */
    public InstanceTypeSeriesQuota withLimit(long limit) {
        this.limit = limit;
        return this;
    }

    /**
     * Get the used property: Number of units currently in use.
     *
     * @return the used value.
     */
    public Long used() {
        return this.used;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (id() == null) {
            throw LOGGER
                .logExceptionAsError(
                    new IllegalArgumentException("Missing required property id in model InstanceTypeSeriesQuota"));
        }
    }

    private static final ClientLogger LOGGER = new ClientLogger(InstanceTypeSeriesQuota.class);
}
