// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.singularity.models;

import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collection;

/** Defines values for MountOptionsKind. */
public final class MountOptionsKind extends ExpandableStringEnum<MountOptionsKind> {
    /** Static value Fuse for MountOptionsKind. */
    public static final MountOptionsKind FUSE = fromString("Fuse");

    /** Static value Interception for MountOptionsKind. */
    public static final MountOptionsKind INTERCEPTION = fromString("Interception");

    /**
     * Creates or finds a MountOptionsKind from its string representation.
     *
     * @param name a name to look for.
     * @return the corresponding MountOptionsKind.
     */
    @JsonCreator
    public static MountOptionsKind fromString(String name) {
        return fromString(name, MountOptionsKind.class);
    }

    /**
     * Gets known MountOptionsKind values.
     *
     * @return known MountOptionsKind values.
     */
    public static Collection<MountOptionsKind> values() {
        return values(MountOptionsKind.class);
    }
}
