// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.singularity.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The ResourceSystemData model. */
@Immutable
public final class ResourceSystemData {
    /*
     * A string identifier for the identity that created the resource.
     */
    @JsonProperty(value = "createdBy", access = JsonProperty.Access.WRITE_ONLY)
    private String createdBy;

    /*
     * The type of identity that created the resource: user, application,
     * managedIdentity, key.
     */
    @JsonProperty(value = "createdByType", access = JsonProperty.Access.WRITE_ONLY)
    private String createdByType;

    /*
     * The timestamp of resource creation (UTC).
     */
    @JsonProperty(value = "createdAt", access = JsonProperty.Access.WRITE_ONLY)
    private String createdAt;

    /*
     * A string identifier for the identity that last modified the resource
     */
    @JsonProperty(value = "lastModifiedBy", access = JsonProperty.Access.WRITE_ONLY)
    private String lastModifiedBy;

    /*
     * The type of identity that last modified the resource: user, application,
     * managedIdentity, key.
     */
    @JsonProperty(value = "lastModifiedByType", access = JsonProperty.Access.WRITE_ONLY)
    private String lastModifiedByType;

    /*
     * The timestamp of resource last modification (UTC).
     */
    @JsonProperty(value = "lastModifiedAt", access = JsonProperty.Access.WRITE_ONLY)
    private String lastModifiedAt;

    /**
     * Get the createdBy property: A string identifier for the identity that created the resource.
     *
     * @return the createdBy value.
     */
    public String createdBy() {
        return this.createdBy;
    }

    /**
     * Get the createdByType property: The type of identity that created the resource: user, application,
     * managedIdentity, key.
     *
     * @return the createdByType value.
     */
    public String createdByType() {
        return this.createdByType;
    }

    /**
     * Get the createdAt property: The timestamp of resource creation (UTC).
     *
     * @return the createdAt value.
     */
    public String createdAt() {
        return this.createdAt;
    }

    /**
     * Get the lastModifiedBy property: A string identifier for the identity that last modified the resource.
     *
     * @return the lastModifiedBy value.
     */
    public String lastModifiedBy() {
        return this.lastModifiedBy;
    }

    /**
     * Get the lastModifiedByType property: The type of identity that last modified the resource: user, application,
     * managedIdentity, key.
     *
     * @return the lastModifiedByType value.
     */
    public String lastModifiedByType() {
        return this.lastModifiedByType;
    }

    /**
     * Get the lastModifiedAt property: The timestamp of resource last modification (UTC).
     *
     * @return the lastModifiedAt value.
     */
    public String lastModifiedAt() {
        return this.lastModifiedAt;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }
}
