// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.analytics.purview.account;

import com.azure.core.http.HttpClient;
import com.azure.core.http.policy.HttpLogDetailLevel;
import com.azure.core.http.policy.HttpLogOptions;
import com.azure.core.test.TestBase;
import com.azure.core.test.TestMode;
import com.azure.core.test.annotation.DoNotRecord;
import com.azure.core.util.Configuration;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public final class ClientTests extends TestBase {
    private AccountsClient accountsClient;

    private CollectionsClient collectionsClient;

    private ResourceSetRulesClient resourceSetRulesClient;

    @BeforeEach
    public void setup() {
        AccountsClientBuilder accountsClientbuilder =
                new AccountsClientBuilder()
                        .endpoint(Configuration.getGlobalConfiguration().get("ENDPOINT"))
                        .httpClient(HttpClient.createDefault())
                        .httpLogOptions(new HttpLogOptions().setLogLevel(HttpLogDetailLevel.BASIC));
        if (getTestMode() == TestMode.PLAYBACK) {
            accountsClientbuilder.httpClient(interceptorManager.getPlaybackClient());
        } else if (getTestMode() == TestMode.RECORD) {
            accountsClientbuilder.addPolicy(interceptorManager.getRecordPolicy());
        }
        accountsClient = accountsClientbuilder.buildClient();

        CollectionsClientBuilder collectionsClientbuilder =
                new CollectionsClientBuilder()
                        .endpoint(Configuration.getGlobalConfiguration().get("ENDPOINT"))
                        .httpClient(HttpClient.createDefault())
                        .httpLogOptions(new HttpLogOptions().setLogLevel(HttpLogDetailLevel.BASIC));
        if (getTestMode() == TestMode.PLAYBACK) {
            collectionsClientbuilder.httpClient(interceptorManager.getPlaybackClient());
        } else if (getTestMode() == TestMode.RECORD) {
            collectionsClientbuilder.addPolicy(interceptorManager.getRecordPolicy());
        }
        collectionsClient = collectionsClientbuilder.buildClient();

        ResourceSetRulesClientBuilder resourceSetRulesClientbuilder =
                new ResourceSetRulesClientBuilder()
                        .endpoint(Configuration.getGlobalConfiguration().get("ENDPOINT"))
                        .httpClient(HttpClient.createDefault())
                        .httpLogOptions(new HttpLogOptions().setLogLevel(HttpLogDetailLevel.BASIC));
        if (getTestMode() == TestMode.PLAYBACK) {
            resourceSetRulesClientbuilder.httpClient(interceptorManager.getPlaybackClient());
        } else if (getTestMode() == TestMode.RECORD) {
            resourceSetRulesClientbuilder.addPolicy(interceptorManager.getRecordPolicy());
        }
        resourceSetRulesClient = resourceSetRulesClientbuilder.buildClient();
    }

    @Test
    @DoNotRecord(skipInPlayback = true)
    public void testClient() {
        // use the builder to create client
    }
}
