# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/containerservice/ci.yml
      - sdk/containerservice/azure-resourcemanager-containerservice-generated/
    exclude:
      - sdk/containerservice/pom.xml
      - sdk/containerservice/azure-resourcemanager-containerservice-generated/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/containerservice/ci.yml
      - sdk/containerservice/azure-resourcemanager-containerservice-generated/
    exclude:
      - sdk/containerservice/pom.xml
      - sdk/containerservice/azure-resourcemanager-containerservice-generated/pom.xml

parameters:
  - name: release_azureresourcemanagercontainerservicegenerated
    displayName: azure-resourcemanager-containerservice-generated
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: containerservice
    EnableBatchRelease: true
    Artifacts:
      - name: azure-resourcemanager-containerservice-generated
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagercontainerservicegenerated
        releaseInBatch: ${{ parameters.release_azureresourcemanagercontainerservicegenerated }}
