// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.healthcareapis.models;

import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collection;

/** Defines values for AnalyticsConnectorMappingType. */
public final class AnalyticsConnectorMappingType extends ExpandableStringEnum<AnalyticsConnectorMappingType> {
    /** Static value fhirToParquet for AnalyticsConnectorMappingType. */
    public static final AnalyticsConnectorMappingType FHIR_TO_PARQUET = fromString("fhirToParquet");

    /**
     * Creates or finds a AnalyticsConnectorMappingType from its string representation.
     *
     * @param name a name to look for.
     * @return the corresponding AnalyticsConnectorMappingType.
     */
    @JsonCreator
    public static AnalyticsConnectorMappingType fromString(String name) {
        return fromString(name, AnalyticsConnectorMappingType.class);
    }

    /**
     * Gets known AnalyticsConnectorMappingType values.
     *
     * @return known AnalyticsConnectorMappingType values.
     */
    public static Collection<AnalyticsConnectorMappingType> values() {
        return values(AnalyticsConnectorMappingType.class);
    }
}
