// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.healthcareapis.models;

import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collection;

/** Defines values for AnalyticsConnectorDataDestinationType. */
public final class AnalyticsConnectorDataDestinationType
    extends ExpandableStringEnum<AnalyticsConnectorDataDestinationType> {
    /** Static value datalake for AnalyticsConnectorDataDestinationType. */
    public static final AnalyticsConnectorDataDestinationType DATALAKE = fromString("datalake");

    /**
     * Creates or finds a AnalyticsConnectorDataDestinationType from its string representation.
     *
     * @param name a name to look for.
     * @return the corresponding AnalyticsConnectorDataDestinationType.
     */
    @JsonCreator
    public static AnalyticsConnectorDataDestinationType fromString(String name) {
        return fromString(name, AnalyticsConnectorDataDestinationType.class);
    }

    /**
     * Gets known AnalyticsConnectorDataDestinationType values.
     *
     * @return known AnalyticsConnectorDataDestinationType values.
     */
    public static Collection<AnalyticsConnectorDataDestinationType> values() {
        return values(AnalyticsConnectorDataDestinationType.class);
    }
}
