# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/demoservice/ci.yml
      - sdk/demoservice/azure-newservices-demo/
    exclude:
      - sdk/demoservice/pom.xml
      - sdk/demoservice/azure-newservices-demo/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/demoservice/ci.yml
      - sdk/demoservice/azure-newservices-demo/
    exclude:
      - sdk/demoservice/pom.xml
      - sdk/demoservice/azure-newservices-demo/pom.xml

parameters:
  - name: release_azurenewservicesdemo
    displayName: azure-newservices-demo
    type: boolean
    default: true

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: demoservice
    EnableBatchRelease: true
    Artifacts:
      - name: azure-newservices-demo
        groupId: com.azure
        safeName: azurenewservicesdemo
        releaseInBatch: ${{ parameters.release_azurenewservicesdemo }}
