// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.devtestlabs.models;

import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collection;

/** Defines values for ImageType. */
public final class ImageType extends ExpandableStringEnum<ImageType> {
    /** Static value Generalized for ImageType. */
    public static final ImageType GENERALIZED = fromString("Generalized");

    /** Static value Specialized for ImageType. */
    public static final ImageType SPECIALIZED = fromString("Specialized");

    /**
     * Creates or finds a ImageType from its string representation.
     *
     * @param name a name to look for.
     * @return the corresponding ImageType.
     */
    @JsonCreator
    public static ImageType fromString(String name) {
        return fromString(name, ImageType.class);
    }

    /**
     * Gets known ImageType values.
     *
     * @return known ImageType values.
     */
    public static Collection<ImageType> values() {
        return values(ImageType.class);
    }
}
