// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.devtestlabs.models;

import com.azure.core.management.Region;
import com.azure.core.management.SystemData;
import com.azure.core.util.Context;
import com.azure.resourcemanager.devtestlabs.fluent.models.SharedGalleryInner;
import java.util.Map;

/** An immutable client-side representation of SharedGallery. */
public interface SharedGallery {
    /**
     * Gets the id property: Fully qualified resource Id for the resource.
     *
     * @return the id value.
     */
    String id();

    /**
     * Gets the name property: The name of the resource.
     *
     * @return the name value.
     */
    String name();

    /**
     * Gets the type property: The type of the resource.
     *
     * @return the type value.
     */
    String type();

    /**
     * Gets the location property: The geo-location where the resource lives.
     *
     * @return the location value.
     */
    String location();

    /**
     * Gets the tags property: Resource tags.
     *
     * @return the tags value.
     */
    Map<String, String> tags();

    /**
     * Gets the systemData property: The system metadata relating to this resource.
     *
     * @return the systemData value.
     */
    SystemData systemData();

    /**
     * Gets the galleryId property: The shared image gallery resource Id.
     *
     * @return the galleryId value.
     */
    String galleryId();

    /**
     * Gets the allowAllImages property: Enables all images in the gallery to be available in the lab for VM creation.
     * This will override the EnableState on shared images.
     *
     * @return the allowAllImages value.
     */
    EnableState allowAllImages();

    /**
     * Gets the provisioningState property: The provisioning status of the resource.
     *
     * @return the provisioningState value.
     */
    String provisioningState();

    /**
     * Gets the uniqueIdentifier property: The unique immutable identifier of a resource (Guid).
     *
     * @return the uniqueIdentifier value.
     */
    String uniqueIdentifier();

    /**
     * Gets the region of the resource.
     *
     * @return the region of the resource.
     */
    Region region();

    /**
     * Gets the name of the resource region.
     *
     * @return the name of the resource region.
     */
    String regionName();

    /**
     * Gets the name of the resource group.
     *
     * @return the name of the resource group.
     */
    String resourceGroupName();

    /**
     * Gets the inner com.azure.resourcemanager.devtestlabs.fluent.models.SharedGalleryInner object.
     *
     * @return the inner object.
     */
    SharedGalleryInner innerModel();

    /** The entirety of the SharedGallery definition. */
    interface Definition
        extends DefinitionStages.Blank,
            DefinitionStages.WithLocation,
            DefinitionStages.WithParentResource,
            DefinitionStages.WithCreate {
    }
    /** The SharedGallery definition stages. */
    interface DefinitionStages {
        /** The first stage of the SharedGallery definition. */
        interface Blank extends WithLocation {
        }
        /** The stage of the SharedGallery definition allowing to specify location. */
        interface WithLocation {
            /**
             * Specifies the region for the resource.
             *
             * @param location The geo-location where the resource lives.
             * @return the next definition stage.
             */
            WithParentResource withRegion(Region location);

            /**
             * Specifies the region for the resource.
             *
             * @param location The geo-location where the resource lives.
             * @return the next definition stage.
             */
            WithParentResource withRegion(String location);
        }
        /** The stage of the SharedGallery definition allowing to specify parent resource. */
        interface WithParentResource {
            /**
             * Specifies resourceGroupName, labName.
             *
             * @param resourceGroupName The name of the resource group.
             * @param labName The name of the lab.
             * @return the next definition stage.
             */
            WithCreate withExistingLab(String resourceGroupName, String labName);
        }
        /**
         * The stage of the SharedGallery definition which contains all the minimum required properties for the resource
         * to be created, but also allows for any other optional properties to be specified.
         */
        interface WithCreate
            extends DefinitionStages.WithTags, DefinitionStages.WithGalleryId, DefinitionStages.WithAllowAllImages {
            /**
             * Executes the create request.
             *
             * @return the created resource.
             */
            SharedGallery create();

            /**
             * Executes the create request.
             *
             * @param context The context to associate with this operation.
             * @return the created resource.
             */
            SharedGallery create(Context context);
        }
        /** The stage of the SharedGallery definition allowing to specify tags. */
        interface WithTags {
            /**
             * Specifies the tags property: Resource tags..
             *
             * @param tags Resource tags.
             * @return the next definition stage.
             */
            WithCreate withTags(Map<String, String> tags);
        }
        /** The stage of the SharedGallery definition allowing to specify galleryId. */
        interface WithGalleryId {
            /**
             * Specifies the galleryId property: The shared image gallery resource Id.
             *
             * @param galleryId The shared image gallery resource Id.
             * @return the next definition stage.
             */
            WithCreate withGalleryId(String galleryId);
        }
        /** The stage of the SharedGallery definition allowing to specify allowAllImages. */
        interface WithAllowAllImages {
            /**
             * Specifies the allowAllImages property: Enables all images in the gallery to be available in the lab for
             * VM creation. This will override the EnableState on shared images.
             *
             * @param allowAllImages Enables all images in the gallery to be available in the lab for VM creation. This
             *     will override the EnableState on shared images.
             * @return the next definition stage.
             */
            WithCreate withAllowAllImages(EnableState allowAllImages);
        }
    }
    /**
     * Begins update for the SharedGallery resource.
     *
     * @return the stage of resource update.
     */
    SharedGallery.Update update();

    /** The template for SharedGallery update. */
    interface Update extends UpdateStages.WithTags {
        /**
         * Executes the update request.
         *
         * @return the updated resource.
         */
        SharedGallery apply();

        /**
         * Executes the update request.
         *
         * @param context The context to associate with this operation.
         * @return the updated resource.
         */
        SharedGallery apply(Context context);
    }
    /** The SharedGallery update stages. */
    interface UpdateStages {
        /** The stage of the SharedGallery update allowing to specify tags. */
        interface WithTags {
            /**
             * Specifies the tags property: The tags of the resource..
             *
             * @param tags The tags of the resource.
             * @return the next definition stage.
             */
            Update withTags(Map<String, String> tags);
        }
    }
    /**
     * Refreshes the resource to sync with Azure.
     *
     * @return the refreshed resource.
     */
    SharedGallery refresh();

    /**
     * Refreshes the resource to sync with Azure.
     *
     * @param context The context to associate with this operation.
     * @return the refreshed resource.
     */
    SharedGallery refresh(Context context);
}
