// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.devtestlabs.models;

import com.azure.core.annotation.Fluent;
import com.azure.resourcemanager.devtestlabs.fluent.models.SharedGalleryInner;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** Contains a list of sharedGalleries and their properties. */
@Fluent
public final class SharedGalleryList {
    /*
     * List of sharedGalleries and their properties
     */
    @JsonProperty(value = "value")
    private List<SharedGalleryInner> value;

    /*
     * URL to get the next set of operation list results if there are any
     */
    @JsonProperty(value = "nextLink")
    private String nextLink;

    /**
     * Get the value property: List of sharedGalleries and their properties.
     *
     * @return the value value.
     */
    public List<SharedGalleryInner> value() {
        return this.value;
    }

    /**
     * Set the value property: List of sharedGalleries and their properties.
     *
     * @param value the value value to set.
     * @return the SharedGalleryList object itself.
     */
    public SharedGalleryList withValue(List<SharedGalleryInner> value) {
        this.value = value;
        return this;
    }

    /**
     * Get the nextLink property: URL to get the next set of operation list results if there are any.
     *
     * @return the nextLink value.
     */
    public String nextLink() {
        return this.nextLink;
    }

    /**
     * Set the nextLink property: URL to get the next set of operation list results if there are any.
     *
     * @param nextLink the nextLink value to set.
     * @return the SharedGalleryList object itself.
     */
    public SharedGalleryList withNextLink(String nextLink) {
        this.nextLink = nextLink;
        return this;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (value() != null) {
            value().forEach(e -> e.validate());
        }
    }
}
