// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.security.models;

import com.azure.resourcemanager.security.fluent.models.ScannerConfigurationListInner;
import java.util.List;

/** An immutable client-side representation of ScannerConfigurationList. */
public interface ScannerConfigurationList {
    /**
     * Gets the value property: The value property.
     *
     * @return the value value.
     */
    List<ScannerConfiguration> value();

    /**
     * Gets the inner com.azure.resourcemanager.security.fluent.models.ScannerConfigurationListInner object.
     *
     * @return the inner object.
     */
    ScannerConfigurationListInner innerModel();
}
