// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

module com.azure.resourcemanager.releaseplannertest {
    requires transitive com.azure.core.management;

    exports com.azure.resourcemanager.releaseplannertest;
    exports com.azure.resourcemanager.releaseplannertest.fluent;
    exports com.azure.resourcemanager.releaseplannertest.fluent.models;
    exports com.azure.resourcemanager.releaseplannertest.models;

    opens com.azure.resourcemanager.releaseplannertest.fluent.models to
        com.azure.core,
        com.fasterxml.jackson.databind;
    opens com.azure.resourcemanager.releaseplannertest.models to
        com.azure.core,
        com.fasterxml.jackson.databind;
}
