# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - master
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/authorization/

pr:
  branches:
    include:
      - master
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/authorization/

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: authorization
    Artifacts:
      - name: azure-resourcemanager-authorization-generated
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerauthorizationgenerated
