# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/authorization/ci.yml
      - sdk/authorization/azure-resourcemanager-authorization-generated/
    exclude:
      - sdk/authorization/pom.xml
      - sdk/authorization/azure-resourcemanager-authorization-generated/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/authorization/ci.yml
      - sdk/authorization/azure-resourcemanager-authorization-generated/
    exclude:
      - sdk/authorization/pom.xml
      - sdk/authorization/azure-resourcemanager-authorization-generated/pom.xml

parameters:
  - name: release_azureresourcemanagerauthorizationgenerated
    displayName: azure-resourcemanager-authorization-generated
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: authorization
    EnableBatchRelease: true
    Artifacts:
      - name: azure-resourcemanager-authorization-generated
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerauthorizationgenerated
        releaseInBatch: ${{ parameters.release_azureresourcemanagerauthorizationgenerated }}
