// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

module com.azure.eventgrid.messaging {
    requires transitive com.azure.core;

    exports com.azure.eventgrid.messaging;
    exports com.azure.eventgrid.messaging.models;

    opens com.azure.eventgrid.messaging.models to
            com.azure.core,
            com.fasterxml.jackson.databind;
}
