// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.singularity.fluent.models;

import com.azure.core.annotation.Fluent;
import com.azure.resourcemanager.singularity.models.AccountLocation;
import com.azure.resourcemanager.singularity.models.AccountPatchProperties;
import com.azure.resourcemanager.singularity.models.IdleResourcesHandlingPolicy;
import com.azure.resourcemanager.singularity.models.NetworkSettings;
import java.util.List;

/** The AccountResourcePatchDescriptionProperties model. */
@Fluent
public final class AccountResourcePatchDescriptionProperties extends AccountPatchProperties {
    /** {@inheritDoc} */
    @Override
    public AccountResourcePatchDescriptionProperties withDescription(String description) {
        super.withDescription(description);
        return this;
    }

    /** {@inheritDoc} */
    @Override
    public AccountResourcePatchDescriptionProperties withIdleResourcesHandlingPolicy(
        IdleResourcesHandlingPolicy idleResourcesHandlingPolicy) {
        super.withIdleResourcesHandlingPolicy(idleResourcesHandlingPolicy);
        return this;
    }

    /** {@inheritDoc} */
    @Override
    public AccountResourcePatchDescriptionProperties withLocations(List<AccountLocation> locations) {
        super.withLocations(locations);
        return this;
    }

    /** {@inheritDoc} */
    @Override
    public AccountResourcePatchDescriptionProperties withNetworkSettings(NetworkSettings networkSettings) {
        super.withNetworkSettings(networkSettings);
        return this;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    @Override
    public void validate() {
        super.validate();
    }
}
