# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/scan/ci.yml
      - sdk/scan/azure-resourcemanager-scan/
    exclude:
      - sdk/scan/pom.xml
      - sdk/scan/azure-resourcemanager-scan/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/scan/ci.yml
      - sdk/scan/azure-resourcemanager-scan/
    exclude:
      - sdk/scan/pom.xml
      - sdk/scan/azure-resourcemanager-scan/pom.xml

parameters:
  - name: release_azureresourcemanagerscan
    displayName: azure-resourcemanager-scan
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: scan
    EnableBatchRelease: true
    Artifacts:
      - name: azure-resourcemanager-scan
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerscan
        releaseInBatch: ${{ parameters.release_azureresourcemanagerscan }}
