# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/dns/ci.yml
      - sdk/dns/azure-resourcemanager-dns-generated/
    exclude:
      - sdk/dns/pom.xml
      - sdk/dns/azure-resourcemanager-dns-generated/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/dns/ci.yml
      - sdk/dns/azure-resourcemanager-dns-generated/
    exclude:
      - sdk/dns/pom.xml
      - sdk/dns/azure-resourcemanager-dns-generated/pom.xml

parameters:
  - name: release_azureresourcemanagerdnsgenerated
    displayName: azure-resourcemanager-dns-generated
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: dns
    EnableBatchRelease: true
    Artifacts:
      - name: azure-resourcemanager-dns-generated
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerdnsgenerated
        releaseInBatch: ${{ parameters.release_azureresourcemanagerdnsgenerated }}
