/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.appplatform.v2019_05_01_preview.implementation;

import com.microsoft.azure.management.appplatform.v2019_05_01_preview.CustomDomainProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.microsoft.azure.ProxyResource;

/**
 * Custom domain resource payload.
 */
public class CustomDomainResourceInner extends ProxyResource {
    /**
     * Properties of the custom domain resource.
     */
    @JsonProperty(value = "properties")
    private CustomDomainProperties properties;

    /**
     * The location property.
     */
    @JsonProperty(value = "location")
    private String location;

    /**
     * Get properties of the custom domain resource.
     *
     * @return the properties value
     */
    public CustomDomainProperties properties() {
        return this.properties;
    }

    /**
     * Set properties of the custom domain resource.
     *
     * @param properties the properties value to set
     * @return the CustomDomainResourceInner object itself.
     */
    public CustomDomainResourceInner withProperties(CustomDomainProperties properties) {
        this.properties = properties;
        return this;
    }

    /**
     * Get the location value.
     *
     * @return the location value
     */
    public String location() {
        return this.location;
    }

    /**
     * Set the location value.
     *
     * @param location the location value to set
     * @return the CustomDomainResourceInner object itself.
     */
    public CustomDomainResourceInner withLocation(String location) {
        this.location = location;
        return this;
    }

}
