# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - master
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/devops/

pr:
  branches:
    include:
      - master
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/devops/

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: devops
    Artifacts:
      - name: azure-resourcemanager-devops
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerdevops
