// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.securityinsights.fluent.models;

import com.azure.core.annotation.Fluent;
import com.azure.resourcemanager.securityinsights.models.ResourceWithEtag;
import com.azure.resourcemanager.securityinsights.models.UserInfo;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;

/** Represents a Query in Azure Security Insights. */
@Fluent
public final class QueryInner extends ResourceWithEtag {
    /*
     * Query properties
     */
    @JsonProperty(value = "properties")
    private QueryProperties innerProperties;

    /**
     * Get the innerProperties property: Query properties.
     *
     * @return the innerProperties value.
     */
    private QueryProperties innerProperties() {
        return this.innerProperties;
    }

    /** {@inheritDoc} */
    @Override
    public QueryInner withEtag(String etag) {
        super.withEtag(etag);
        return this;
    }

    /**
     * Get the queryId property: The id (a Guid) of the query.
     *
     * @return the queryId value.
     */
    public String queryId() {
        return this.innerProperties() == null ? null : this.innerProperties().queryId();
    }

    /**
     * Set the queryId property: The id (a Guid) of the query.
     *
     * @param queryId the queryId value to set.
     * @return the QueryInner object itself.
     */
    public QueryInner withQueryId(String queryId) {
        if (this.innerProperties() == null) {
            this.innerProperties = new QueryProperties();
        }
        this.innerProperties().withQueryId(queryId);
        return this;
    }

    /**
     * Get the correlationId property: The id (a Guid) of the correlationId.
     *
     * @return the correlationId value.
     */
    public String correlationId() {
        return this.innerProperties() == null ? null : this.innerProperties().correlationId();
    }

    /**
     * Set the correlationId property: The id (a Guid) of the correlationId.
     *
     * @param correlationId the correlationId value to set.
     * @return the QueryInner object itself.
     */
    public QueryInner withCorrelationId(String correlationId) {
        if (this.innerProperties() == null) {
            this.innerProperties = new QueryProperties();
        }
        this.innerProperties().withCorrelationId(correlationId);
        return this;
    }

    /**
     * Get the naturalLanguage property: The natural language.
     *
     * @return the naturalLanguage value.
     */
    public String naturalLanguage() {
        return this.innerProperties() == null ? null : this.innerProperties().naturalLanguage();
    }

    /**
     * Set the naturalLanguage property: The natural language.
     *
     * @param naturalLanguage the naturalLanguage value to set.
     * @return the QueryInner object itself.
     */
    public QueryInner withNaturalLanguage(String naturalLanguage) {
        if (this.innerProperties() == null) {
            this.innerProperties = new QueryProperties();
        }
        this.innerProperties().withNaturalLanguage(naturalLanguage);
        return this;
    }

    /**
     * Get the kustoQueryLanguage property: the kusto query for a natural language.
     *
     * @return the kustoQueryLanguage value.
     */
    public String kustoQueryLanguage() {
        return this.innerProperties() == null ? null : this.innerProperties().kustoQueryLanguage();
    }

    /**
     * Set the kustoQueryLanguage property: the kusto query for a natural language.
     *
     * @param kustoQueryLanguage the kustoQueryLanguage value to set.
     * @return the QueryInner object itself.
     */
    public QueryInner withKustoQueryLanguage(String kustoQueryLanguage) {
        if (this.innerProperties() == null) {
            this.innerProperties = new QueryProperties();
        }
        this.innerProperties().withKustoQueryLanguage(kustoQueryLanguage);
        return this;
    }

    /**
     * Get the created property: The time the query was created.
     *
     * @return the created value.
     */
    public OffsetDateTime created() {
        return this.innerProperties() == null ? null : this.innerProperties().created();
    }

    /**
     * Set the created property: The time the query was created.
     *
     * @param created the created value to set.
     * @return the QueryInner object itself.
     */
    public QueryInner withCreated(OffsetDateTime created) {
        if (this.innerProperties() == null) {
            this.innerProperties = new QueryProperties();
        }
        this.innerProperties().withCreated(created);
        return this;
    }

    /**
     * Get the updated property: The last time the query was updated.
     *
     * @return the updated value.
     */
    public OffsetDateTime updated() {
        return this.innerProperties() == null ? null : this.innerProperties().updated();
    }

    /**
     * Set the updated property: The last time the query was updated.
     *
     * @param updated the updated value to set.
     * @return the QueryInner object itself.
     */
    public QueryInner withUpdated(OffsetDateTime updated) {
        if (this.innerProperties() == null) {
            this.innerProperties = new QueryProperties();
        }
        this.innerProperties().withUpdated(updated);
        return this;
    }

    /**
     * Get the createdBy property: Describes a user that created the query.
     *
     * @return the createdBy value.
     */
    public UserInfo createdBy() {
        return this.innerProperties() == null ? null : this.innerProperties().createdBy();
    }

    /**
     * Set the createdBy property: Describes a user that created the query.
     *
     * @param createdBy the createdBy value to set.
     * @return the QueryInner object itself.
     */
    public QueryInner withCreatedBy(UserInfo createdBy) {
        if (this.innerProperties() == null) {
            this.innerProperties = new QueryProperties();
        }
        this.innerProperties().withCreatedBy(createdBy);
        return this;
    }

    /**
     * Get the updatedBy property: Describes a user that updated the query.
     *
     * @return the updatedBy value.
     */
    public UserInfo updatedBy() {
        return this.innerProperties() == null ? null : this.innerProperties().updatedBy();
    }

    /**
     * Set the updatedBy property: Describes a user that updated the query.
     *
     * @param updatedBy the updatedBy value to set.
     * @return the QueryInner object itself.
     */
    public QueryInner withUpdatedBy(UserInfo updatedBy) {
        if (this.innerProperties() == null) {
            this.innerProperties = new QueryProperties();
        }
        this.innerProperties().withUpdatedBy(updatedBy);
        return this;
    }

    /**
     * Get the documentType property: A type of the document (is 'assistedQuery').
     *
     * @return the documentType value.
     */
    public String documentType() {
        return this.innerProperties() == null ? null : this.innerProperties().documentType();
    }

    /**
     * Set the documentType property: A type of the document (is 'assistedQuery').
     *
     * @param documentType the documentType value to set.
     * @return the QueryInner object itself.
     */
    public QueryInner withDocumentType(String documentType) {
        if (this.innerProperties() == null) {
            this.innerProperties = new QueryProperties();
        }
        this.innerProperties().withDocumentType(documentType);
        return this;
    }

    /**
     * Get the executionResult property: The result of the execution to get kusto query from natural language input.
     *
     * @return the executionResult value.
     */
    public String executionResult() {
        return this.innerProperties() == null ? null : this.innerProperties().executionResult();
    }

    /**
     * Set the executionResult property: The result of the execution to get kusto query from natural language input.
     *
     * @param executionResult the executionResult value to set.
     * @return the QueryInner object itself.
     */
    public QueryInner withExecutionResult(String executionResult) {
        if (this.innerProperties() == null) {
            this.innerProperties = new QueryProperties();
        }
        this.innerProperties().withExecutionResult(executionResult);
        return this;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    @Override
    public void validate() {
        super.validate();
        if (innerProperties() != null) {
            innerProperties().validate();
        }
    }
}
