// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.devtestlabs.fluent.models;

import com.azure.core.annotation.Fluent;
import com.azure.resourcemanager.devtestlabs.models.EnableState;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Properties of a shared gallery. */
@Fluent
public final class SharedGalleryProperties {
    /*
     * The shared image gallery resource Id
     */
    @JsonProperty(value = "galleryId")
    private String galleryId;

    /*
     * Enables all images in the gallery to be available in the lab for VM
     * creation. This will override the EnableState on shared images
     */
    @JsonProperty(value = "allowAllImages")
    private EnableState allowAllImages;

    /*
     * The provisioning status of the resource.
     */
    @JsonProperty(value = "provisioningState", access = JsonProperty.Access.WRITE_ONLY)
    private String provisioningState;

    /*
     * The unique immutable identifier of a resource (Guid).
     */
    @JsonProperty(value = "uniqueIdentifier", access = JsonProperty.Access.WRITE_ONLY)
    private String uniqueIdentifier;

    /**
     * Get the galleryId property: The shared image gallery resource Id.
     *
     * @return the galleryId value.
     */
    public String galleryId() {
        return this.galleryId;
    }

    /**
     * Set the galleryId property: The shared image gallery resource Id.
     *
     * @param galleryId the galleryId value to set.
     * @return the SharedGalleryProperties object itself.
     */
    public SharedGalleryProperties withGalleryId(String galleryId) {
        this.galleryId = galleryId;
        return this;
    }

    /**
     * Get the allowAllImages property: Enables all images in the gallery to be available in the lab for VM creation.
     * This will override the EnableState on shared images.
     *
     * @return the allowAllImages value.
     */
    public EnableState allowAllImages() {
        return this.allowAllImages;
    }

    /**
     * Set the allowAllImages property: Enables all images in the gallery to be available in the lab for VM creation.
     * This will override the EnableState on shared images.
     *
     * @param allowAllImages the allowAllImages value to set.
     * @return the SharedGalleryProperties object itself.
     */
    public SharedGalleryProperties withAllowAllImages(EnableState allowAllImages) {
        this.allowAllImages = allowAllImages;
        return this;
    }

    /**
     * Get the provisioningState property: The provisioning status of the resource.
     *
     * @return the provisioningState value.
     */
    public String provisioningState() {
        return this.provisioningState;
    }

    /**
     * Get the uniqueIdentifier property: The unique immutable identifier of a resource (Guid).
     *
     * @return the uniqueIdentifier value.
     */
    public String uniqueIdentifier() {
        return this.uniqueIdentifier;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }
}
