// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.contoso_cdn.implementation;

import com.azure.resourcemanager.contoso_cdn.CdnManager;
import com.azure.resourcemanager.contoso_cdn.fluent.models.SsoUriInner;
import com.azure.resourcemanager.contoso_cdn.models.SsoUri;

public final class SsoUriImpl implements SsoUri {
    private SsoUriInner innerObject;

    private final CdnManager serviceManager;

    SsoUriImpl(SsoUriInner innerObject, CdnManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String ssoUriValue() {
        return this.innerModel().ssoUriValue();
    }

    public SsoUriInner innerModel() {
        return this.innerObject;
    }

    private CdnManager manager() {
        return this.serviceManager;
    }
}
