// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.contoso_cdn.implementation;

import com.azure.resourcemanager.contoso_cdn.CdnManager;
import com.azure.resourcemanager.contoso_cdn.fluent.models.ValidateProbeOutputInner;
import com.azure.resourcemanager.contoso_cdn.models.ValidateProbeOutput;

public final class ValidateProbeOutputImpl implements ValidateProbeOutput {
    private ValidateProbeOutputInner innerObject;

    private final CdnManager serviceManager;

    ValidateProbeOutputImpl(ValidateProbeOutputInner innerObject, CdnManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public Boolean isValid() {
        return this.innerModel().isValid();
    }

    public String errorCode() {
        return this.innerModel().errorCode();
    }

    public String message() {
        return this.innerModel().message();
    }

    public ValidateProbeOutputInner innerModel() {
        return this.innerObject;
    }

    private CdnManager manager() {
        return this.serviceManager;
    }
}
