// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.singularity.implementation;

import com.azure.resourcemanager.singularity.fluent.models.ResultInner;
import com.azure.resourcemanager.singularity.models.Result;

public final class ResultImpl implements Result {
    private ResultInner innerObject;

    private final com.azure.resourcemanager.singularity.SingularityManager serviceManager;

    ResultImpl(ResultInner innerObject, com.azure.resourcemanager.singularity.SingularityManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String sampleProperty() {
        return this.innerModel().sampleProperty();
    }

    public ResultInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.singularity.SingularityManager manager() {
        return this.serviceManager;
    }
}
