// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.iot.deviceupdate.demo;

public final class ReadmeSamples {
    public void readmeSamples() {
        // BEGIN: com.azure.iot.deviceupdate.demo.readme
        // END: com.azure.iot.deviceupdate.demo.readme
    }
}
