# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/servicefabricmesh/ci.yml
      - sdk/servicefabricmesh/azure-resourcemanager-servicefabricmesh/
    exclude:
      - sdk/servicefabricmesh/pom.xml
      - sdk/servicefabricmesh/azure-resourcemanager-servicefabricmesh/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/servicefabricmesh/ci.yml
      - sdk/servicefabricmesh/azure-resourcemanager-servicefabricmesh/
    exclude:
      - sdk/servicefabricmesh/pom.xml
      - sdk/servicefabricmesh/azure-resourcemanager-servicefabricmesh/pom.xml

parameters:
  - name: release_azureresourcemanagerservicefabricmesh
    displayName: azure-resourcemanager-servicefabricmesh
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: servicefabricmesh
    EnableBatchRelease: true
    Artifacts:
      - name: azure-resourcemanager-servicefabricmesh
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerservicefabricmesh
        releaseInBatch: ${{ parameters.release_azureresourcemanagerservicefabricmesh }}
