// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.sdkreleaseplannertest.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Details about a Confidential ledger user. */
@Immutable
public final class LedgerUser {
    /*
     * The user id, either an AAD object ID or certificate fingerprint.
     */
    @JsonProperty(value = "userId", required = true, access = JsonProperty.Access.WRITE_ONLY)
    private String userId;

    /*
     * The user's assigned role.
     */
    @JsonProperty(value = "assignedRole", required = true)
    private LedgerUserRole assignedRole;

    /**
     * Creates an instance of LedgerUser class.
     *
     * @param assignedRole the assignedRole value to set.
     */
    @JsonCreator
    public LedgerUser(@JsonProperty(value = "assignedRole", required = true) LedgerUserRole assignedRole) {
        this.assignedRole = assignedRole;
    }

    /**
     * Get the userId property: The user id, either an AAD object ID or certificate fingerprint.
     *
     * @return the userId value.
     */
    public String getUserId() {
        return this.userId;
    }

    /**
     * Get the assignedRole property: The user's assigned role.
     *
     * @return the assignedRole value.
     */
    public LedgerUserRole getAssignedRole() {
        return this.assignedRole;
    }
}
