/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.resourcegraph.v2019_04_01;

import java.util.Collection;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.microsoft.rest.ExpandableStringEnum;

/**
 * Defines values for ResultKind.
 */
public final class ResultKind extends ExpandableStringEnum<ResultKind> {
    /** Static value basic for ResultKind. */
    public static final ResultKind BASIC = fromString("basic");

    /**
     * Creates or finds a ResultKind from its string representation.
     * @param name a name to look for
     * @return the corresponding ResultKind
     */
    @JsonCreator
    public static ResultKind fromString(String name) {
        return fromString(name, ResultKind.class);
    }

    /**
     * @return known ResultKind values
     */
    public static Collection<ResultKind> values() {
        return values(ResultKind.class);
    }
}
