// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.devtestlabs.implementation;

import com.azure.core.http.rest.PagedIterable;
import com.azure.core.http.rest.Response;
import com.azure.core.http.rest.SimpleResponse;
import com.azure.core.util.Context;
import com.azure.core.util.logging.ClientLogger;
import com.azure.resourcemanager.devtestlabs.fluent.SharedImagesClient;
import com.azure.resourcemanager.devtestlabs.fluent.models.SharedImageInner;
import com.azure.resourcemanager.devtestlabs.models.SharedImage;
import com.azure.resourcemanager.devtestlabs.models.SharedImages;

public final class SharedImagesImpl implements SharedImages {
    private static final ClientLogger LOGGER = new ClientLogger(SharedImagesImpl.class);

    private final SharedImagesClient innerClient;

    private final com.azure.resourcemanager.devtestlabs.DevTestLabsManager serviceManager;

    public SharedImagesImpl(
        SharedImagesClient innerClient, com.azure.resourcemanager.devtestlabs.DevTestLabsManager serviceManager) {
        this.innerClient = innerClient;
        this.serviceManager = serviceManager;
    }

    public PagedIterable<SharedImage> list(String resourceGroupName, String labName, String sharedGalleryName) {
        PagedIterable<SharedImageInner> inner =
            this.serviceClient().list(resourceGroupName, labName, sharedGalleryName);
        return Utils.mapPage(inner, inner1 -> new SharedImageImpl(inner1, this.manager()));
    }

    public PagedIterable<SharedImage> list(
        String resourceGroupName,
        String labName,
        String sharedGalleryName,
        String expand,
        String filter,
        Integer top,
        String orderby,
        Context context) {
        PagedIterable<SharedImageInner> inner =
            this
                .serviceClient()
                .list(resourceGroupName, labName, sharedGalleryName, expand, filter, top, orderby, context);
        return Utils.mapPage(inner, inner1 -> new SharedImageImpl(inner1, this.manager()));
    }

    public SharedImage get(String resourceGroupName, String labName, String sharedGalleryName, String name) {
        SharedImageInner inner = this.serviceClient().get(resourceGroupName, labName, sharedGalleryName, name);
        if (inner != null) {
            return new SharedImageImpl(inner, this.manager());
        } else {
            return null;
        }
    }

    public Response<SharedImage> getWithResponse(
        String resourceGroupName,
        String labName,
        String sharedGalleryName,
        String name,
        String expand,
        Context context) {
        Response<SharedImageInner> inner =
            this.serviceClient().getWithResponse(resourceGroupName, labName, sharedGalleryName, name, expand, context);
        if (inner != null) {
            return new SimpleResponse<>(
                inner.getRequest(),
                inner.getStatusCode(),
                inner.getHeaders(),
                new SharedImageImpl(inner.getValue(), this.manager()));
        } else {
            return null;
        }
    }

    public void delete(String resourceGroupName, String labName, String sharedGalleryName, String name) {
        this.serviceClient().delete(resourceGroupName, labName, sharedGalleryName, name);
    }

    public Response<Void> deleteWithResponse(
        String resourceGroupName, String labName, String sharedGalleryName, String name, Context context) {
        return this.serviceClient().deleteWithResponse(resourceGroupName, labName, sharedGalleryName, name, context);
    }

    public SharedImage getById(String id) {
        String resourceGroupName = Utils.getValueFromIdByName(id, "resourceGroups");
        if (resourceGroupName == null) {
            throw LOGGER
                .logExceptionAsError(
                    new IllegalArgumentException(
                        String
                            .format("The resource ID '%s' is not valid. Missing path segment 'resourceGroups'.", id)));
        }
        String labName = Utils.getValueFromIdByName(id, "labs");
        if (labName == null) {
            throw LOGGER
                .logExceptionAsError(
                    new IllegalArgumentException(
                        String.format("The resource ID '%s' is not valid. Missing path segment 'labs'.", id)));
        }
        String sharedGalleryName = Utils.getValueFromIdByName(id, "sharedgalleries");
        if (sharedGalleryName == null) {
            throw LOGGER
                .logExceptionAsError(
                    new IllegalArgumentException(
                        String
                            .format("The resource ID '%s' is not valid. Missing path segment 'sharedgalleries'.", id)));
        }
        String name = Utils.getValueFromIdByName(id, "sharedimages");
        if (name == null) {
            throw LOGGER
                .logExceptionAsError(
                    new IllegalArgumentException(
                        String.format("The resource ID '%s' is not valid. Missing path segment 'sharedimages'.", id)));
        }
        String localExpand = null;
        return this
            .getWithResponse(resourceGroupName, labName, sharedGalleryName, name, localExpand, Context.NONE)
            .getValue();
    }

    public Response<SharedImage> getByIdWithResponse(String id, String expand, Context context) {
        String resourceGroupName = Utils.getValueFromIdByName(id, "resourceGroups");
        if (resourceGroupName == null) {
            throw LOGGER
                .logExceptionAsError(
                    new IllegalArgumentException(
                        String
                            .format("The resource ID '%s' is not valid. Missing path segment 'resourceGroups'.", id)));
        }
        String labName = Utils.getValueFromIdByName(id, "labs");
        if (labName == null) {
            throw LOGGER
                .logExceptionAsError(
                    new IllegalArgumentException(
                        String.format("The resource ID '%s' is not valid. Missing path segment 'labs'.", id)));
        }
        String sharedGalleryName = Utils.getValueFromIdByName(id, "sharedgalleries");
        if (sharedGalleryName == null) {
            throw LOGGER
                .logExceptionAsError(
                    new IllegalArgumentException(
                        String
                            .format("The resource ID '%s' is not valid. Missing path segment 'sharedgalleries'.", id)));
        }
        String name = Utils.getValueFromIdByName(id, "sharedimages");
        if (name == null) {
            throw LOGGER
                .logExceptionAsError(
                    new IllegalArgumentException(
                        String.format("The resource ID '%s' is not valid. Missing path segment 'sharedimages'.", id)));
        }
        return this.getWithResponse(resourceGroupName, labName, sharedGalleryName, name, expand, context);
    }

    public void deleteById(String id) {
        String resourceGroupName = Utils.getValueFromIdByName(id, "resourceGroups");
        if (resourceGroupName == null) {
            throw LOGGER
                .logExceptionAsError(
                    new IllegalArgumentException(
                        String
                            .format("The resource ID '%s' is not valid. Missing path segment 'resourceGroups'.", id)));
        }
        String labName = Utils.getValueFromIdByName(id, "labs");
        if (labName == null) {
            throw LOGGER
                .logExceptionAsError(
                    new IllegalArgumentException(
                        String.format("The resource ID '%s' is not valid. Missing path segment 'labs'.", id)));
        }
        String sharedGalleryName = Utils.getValueFromIdByName(id, "sharedgalleries");
        if (sharedGalleryName == null) {
            throw LOGGER
                .logExceptionAsError(
                    new IllegalArgumentException(
                        String
                            .format("The resource ID '%s' is not valid. Missing path segment 'sharedgalleries'.", id)));
        }
        String name = Utils.getValueFromIdByName(id, "sharedimages");
        if (name == null) {
            throw LOGGER
                .logExceptionAsError(
                    new IllegalArgumentException(
                        String.format("The resource ID '%s' is not valid. Missing path segment 'sharedimages'.", id)));
        }
        this.deleteWithResponse(resourceGroupName, labName, sharedGalleryName, name, Context.NONE);
    }

    public Response<Void> deleteByIdWithResponse(String id, Context context) {
        String resourceGroupName = Utils.getValueFromIdByName(id, "resourceGroups");
        if (resourceGroupName == null) {
            throw LOGGER
                .logExceptionAsError(
                    new IllegalArgumentException(
                        String
                            .format("The resource ID '%s' is not valid. Missing path segment 'resourceGroups'.", id)));
        }
        String labName = Utils.getValueFromIdByName(id, "labs");
        if (labName == null) {
            throw LOGGER
                .logExceptionAsError(
                    new IllegalArgumentException(
                        String.format("The resource ID '%s' is not valid. Missing path segment 'labs'.", id)));
        }
        String sharedGalleryName = Utils.getValueFromIdByName(id, "sharedgalleries");
        if (sharedGalleryName == null) {
            throw LOGGER
                .logExceptionAsError(
                    new IllegalArgumentException(
                        String
                            .format("The resource ID '%s' is not valid. Missing path segment 'sharedgalleries'.", id)));
        }
        String name = Utils.getValueFromIdByName(id, "sharedimages");
        if (name == null) {
            throw LOGGER
                .logExceptionAsError(
                    new IllegalArgumentException(
                        String.format("The resource ID '%s' is not valid. Missing path segment 'sharedimages'.", id)));
        }
        return this.deleteWithResponse(resourceGroupName, labName, sharedGalleryName, name, context);
    }

    private SharedImagesClient serviceClient() {
        return this.innerClient;
    }

    private com.azure.resourcemanager.devtestlabs.DevTestLabsManager manager() {
        return this.serviceManager;
    }

    public SharedImageImpl define(String name) {
        return new SharedImageImpl(name, this.manager());
    }
}
